//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_Data.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Juego()
        {
            this.Cliente_Juego = new HashSet<Cliente_Juego>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_plataforma { get; set; }
        public Nullable<int> id_distribuidor { get; set; }
        public Nullable<int> id_desarrollador { get; set; }
        public Nullable<System.DateTime> fecha_lanzamiento { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente_Juego> Cliente_Juego { get; set; }
        public virtual Desarrollador Desarrollador { get; set; }
        public virtual Distribuidor Distribuidor { get; set; }
        public virtual Plataforma Plataforma { get; set; }
    }
}
